apiVersion: v1
data:
  sso: |
    issuer: https://keycloak.192.168.1.123.nip.io/auth/realms/argo
    sessionExpiry: 24h
    clientId:
      name: client-id-secret
      key: client-id-key
    clientSecret:
      name: client-secret-secret
      key: client-secret-key
    redirectUrl: https://localhost:2746/oauth2/callback
    scopes:
     - groups
     - email
     - profile
     - openid
    rbac:
      enabled: true
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
